Duniverse v1.4.0
dune-universe/mtime pull request #1
Opened 2022-03-15 09:54 UTC by maiste

v1.4.0 2022-02-17 La Forclaz (VS)
---------------------------------

* Change the `js_of_ocaml` strategy for `Mtime_clock`'s JavaScript
  implementation. Primitives of `mtime.clock.os` are now implemented
  in pure JavaScript and linked by `js_of_ocaml`.  This means that the
  `mtime.clock.jsoo` library no longer exists, simply link against
  `mtime.clock.os` instead. Thanks to Hugo Heuzard for suggesting and
  implementing this.

* Add `Mtime.{min,max}_stamp`.
* Add durations `Mtime.Span.{ns,us,ms,s,min,hour,day,year}` and
  the `Mtime.Span.(*)` operator (#28).
* Deprecate `Mtime.s_to_*` and `Mtime.*_to_s` floating point constants (#28).
* Require OCaml >= 4.08.
* Allow compiling with MSVC compiler. Thanks to Jonah Beckford for the patch.

2022-03-15 13:09 UTC, Leonidas-from-XIV requested changes
Apart from the missing `build` line, I think this is very nice. Thanks for contributing the port!

2022-03-15 13:09 UTC, Leonidas-from-XIV commented on mtime.opam
> +tags: [ "time" "posix" "system" "org:erratique" ]
It seems to be missing the `build` line entirely?

2022-03-15 14:47 UTC, Leonidas-from-XIV approved these changes
Looks good! :+1:

2022-03-16 10:04 UTC, merged

2022-05-31 17:19 UTC, patricoferris commented
I might be mistaken, but I think `1.4.0` may need #2 for it to work seamlessly in the browser :))